name: eslint

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    eslint:
      name: run_eslint
      runs-on: ubuntu-18.04
      steps:
        # Install requirements
        - name: Install_requirements
          with:
            node-version: 14
          run: make install
          shell: bash
        # Run ESLint
        - name: Run_ESLint
          run: npx eslint --ext .js,.jsx,.ts,.tsx
          shell: bash
