name: eslint

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    eslint:
      name: run_eslint
      runs-on: ubuntu-18.04
      steps:
        # Pull repositories
        - uses: actions/checkout@v2
        # Setup node
        - uses: actions/setup-node@v1
          name: Setup_node
          with:
            node-version: 14
        # Install requirements
        - name: Install_requirements
          run: npm install
        # Run ESLint
        - name: Run_ESLint
          run: npx eslint --ext .js,.jsx,.ts,.tsx
          shell: bash
