name: eslint

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  verify_files:
    name: Verify Files
    steps:
      - name: Lint Files
        run: node Makefile lint
