name: eslint

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    eslint:
      name: run_eslint
      runs-on: ubuntu-latest
      steps:
        # Run ESLint
        - name: Run_ESLint
          run: make lint
          shell: bash

