name: eslint

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Run ESLint
      - name: Run ESLint
      - run: make lint
